source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"
pod 'JSONModel'
pod 'Shimmer', '~> 1.0.2'
pod 'AFNetworking', '~> 2.6.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'TSMessages', '~> 0.9.12'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell', '= 1.4.beta'
pod 'UIView+FDCollapsibleConstraints', '~> 1.1'
pod 'iOS-blur'
pod 'RKNotificationHub'
pod 'SDCycleScrollView','~> 1.3'
pod 'GRMustache', '~> 7.3.2'
pod 'AMap2DMap'
pod 'AMapLocation'
pod 'MWPhotoBrowser'
pod 'MHTextField', '~> 0.5'
pod 'FMDB'
pod 'FXForms', '~> 1.2.14'
pod 'WeiboSDK'
#pod 'AMapSearch'
#pod 'Realm'
#pod 'SVPullToRefresh', '~> 0.4.1'
#pod 'RESideMenu', '~> 4.0.7'
#pod 'TencentOpenApiSDK', '~> 2.3'
#pod 'SloppySwiper'
#pod 'RWBlurPopover', '~> 3.0.0'
#pod 'BlurryModalSegue'
#pod 'pop', '~> 1.0.7'
#pod 'EAIntroView', '~> 2.6.4'
